### PR TITLE
PotA: fix 2 apostrophe typos

### PR DESCRIPTION
**Pull request by l9f**
Simple little commit. Fixing `Neverwinters` to `Neverwinter's` in two places in PotA.

### CODE REVIEW

**Comment by l9f** [comment]
Oh yeah, great work on the adventures! Sorry I haven't been around much. If you'll post issues you need help with I can take looks at them.

**Comment by l9f** [comment]
Not so sure why the build is failing, unless current master is also failing.

**Comment by TheGiddyLimit** [comment]
Travis broke because the config was removed (we switched to `drone` on the main repo). Don't worry about it (I've just disabled it, hopefully).

As for adventure issues, always happy to have help! Please report them instead of making PRs though; the content is generated from Fantasy Grounds modules via an automated script. I want to stick to changing the script instead of the output for as long as possible.

**Comment by l9f** [comment]
10-4. Will do issues instead of PRs unless you ask. :)

**Pull request closed without merging**
