### PR TITLE
First stab at shaped js builder script

### PR DESCRIPTION
**Pull request by symposion**

### CODE REVIEW

**Comment by symposion** [comment]
Ok, so I've added your cleanup, I've changed to use a class rather than a revealing module and I've added basic homebrew support.

I'm thinking that

1. I should have a manage homebrew button on there somewhere - I'm guessing that's fairly straightforward?
2. I don't like the huge long list with the button at the bottom out of sight - do you think it would be better in a div with a scrollbar?

**Comment by symposion** [comment]
( In case it's not obvious I suck at UI, so feel free to tell me to do stuff completely differently if you have some better ideas - I love what you've done with the 5etools UI!)

**Comment by TheGiddyLimit** [comment]
I, too, suck at UI. But I try.

**Comment by symposion** [comment]
Ok, I've written some usage text now. Let me know what you think. I've included a warning because some Roll20 users can be a little, err, thoughtless, about this stuff - but happy to remove it if you don't think it's appropriate.

**Comment by symposion** [comment]
Ok, don't merge this yet. There's something not right with the homebrew loading that I need to look into

**Comment by symposion** [comment]
Ok, I have fixed the issues that I found, but I've realised that there's something else that needs looking at as well: the sources list on the page needs refreshing after homebrew is updated. I'll take a look at that and send another commit.

One other observation - you're probably already aware of this - when I click to remove one of the homebrew sources from the list, it's extremely slow and chews my CPU for a while. In extreme cases - such as when I have all the available homebrew loaded and I then try and delete Critter Compendium - it actually crashes my Firefox tab (reliably). Interestingly I don't have a problem if I remove everything all in one go with the button at the top - but I guess that just throws all the cached info away etc so that's simpler.

**Comment by symposion** [comment]
Ok, I think I'm done. Let me know if there's anything else that you want changing. I think I've also identified the performance problem I was talking about and I've sent you a separate PR for that to avoid muddying the waters here.

**Pull request merged**
