### PR TITLE
Add 15 and 30 minute/second increments, and 12 hour increments…

### PR DESCRIPTION
**Pull request by Forecaster**
… using CTRL and SHIFT combinations

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
This is exactly what I _didn't_ want to do, as `CTRL` is reserved site-wide as the "don't do any fancy bullshit with my clicks" key modifier. `ALT` doesn't work either, fyi, because Linux uses it for moving windows around.

Not that I have any better ideas at the moment, I haven't sat down and thought about it. Soon:tm:

**Comment by Forecaster** [comment]
I don't see how it can cause any issues when clicking a non-link page button, `CTRL` does things when you click links sure, this hasn't done anything to my setup

**Comment by TheGiddyLimit** [comment]
As in, `CTRL` is used throughout the site to allow circumvention of any default-behaviour-overriding click handlers. Not that it's implemented universally, so there's merit to the idea of doing away with that convention and freeing up the key. Either way, the implications extend further than the functionality of this particular collection of buttons.
So ultimately, again, I'll think about it.

**Comment by Forecaster** [comment]
Ah, I see, I've not encountered that

**Comment by TheGiddyLimit** [comment]
After much debilitation and contemplation (read: about 30 secs), I have come to the conclusion that I cannot be bothered to think up a better button layout for the calendar controls, and therefore deem this a satisfactory solution. 
Added, tyvm.
Closing because merging it into the main codebase and then later merging that back into this repo always causes pain.

**Pull request closed without merging**
