### PR TITLE
Lots more minor formatting fixes, primarily for spells

### PR DESCRIPTION
**Pull request by symposion**
Also added a bunch of data to roll20.json to help populating shaped sheet.

Sorry, this is another beast. I think that's it though (well apart from a few more fixes for Tome of Beasts in homebrew, but I don't think that's anywhere near as bad)

### CODE REVIEW

**Comment by symposion** [comment]
Sorry about the HotDQ thing - it's actually the book that's incorrect! They have 20ft./60ft. *at least in my copy) and I was just blindly following what was there  - I keep forgetting what the actual standard is. Will fix that and the other things and have another pass through to make sure I don't see anything else suspicious.

**Comment by symposion** [comment]
Actually, there are 5 instances in hotdq using 20 ft./60 ft. Do you want me to change all of them to the 20/60 ft. standard?

**Comment by symposion** [comment]
On the dashes/hyphens, I confess that this isn't really my area of expertise. I'm mainly just trying to bring the two different data sources into agreement, and I'm personally not that fussed about the fine details, beyond the general desire to "do things right". All that said, I submit for your examination:

screenshot from 2018-07-23 16-00-56

It seems to me that the dash between the numbers _is_ different to the hyphen used between words normally. I grant you that it's definitely not the same as the long dash for the blank lines of the table - are you sure that isn't something different again? It looks longer than a normal em dash.... 
Either way, happy to just put this back how it was for the moment, but equally happy to try and find the "correct" solution if you wish.

**Comment by symposion** [comment]
Hmm, sorry for the noise, but I've updated my image slightly, and I now see that the long dashes are definitely em dashes:
screenshot from 2018-07-23 16-16-55

I'm wondering what the relationship is between the unary minus dash and the "between the numbers" dash is. In GIMP they're at most a pixel or two different, and I'm wondering if that's actually an anti-aliasing or kerning artefact rather than a different character?

**Comment by TheGiddyLimit** [comment]
I'm happy to believe it's a rendering thing, and that the dashes between numbers are, in fact, en-dashes. There's a reasonable chance they're "figure dashes" (`\u2012`), though, although getting those "perfect" relies on the fonts matching up. If that happens to be the correct solution, then might as well use it, otherwise, no matter. En-dashes are more than close enough.

**Comment by symposion** [comment]
Man, this typography stuff is complicated. When I were a lad, we had to make do with one apostrophe, one quote mark and one dash. If you wanted a longer dash you put two next to each other. Kids and their new-fangled unicode nonsense. Mutter mutter mutter ;-)

**Comment by symposion** [comment]
Ok, I think I've fixed those items now, and I went through  the diff again and I can't see anything else that looks controversial/problematic

**Comment by symposion** [comment]
I just asked Mark who loves all this stuff and he pointed me at this:
https://english.stackexchange.com/questions/2116/when-should-i-use-an-em-dash-an-en-dash-and-a-hyphen
Apparently en dash is the correct character for the number ranges but the unary minus should be a "minus sign" character which is something else again.

**Comment by symposion** [comment]
Based on that info, do we need to consider updating all of the dashes in things like Recharge etc to be en dashes?

**Comment by TheGiddyLimit** [comment]
Well that would explain it. I'm happy to switch to proper minus signs for the unary's (still preferring their unicode version). It would make sense to fix the "Recharge" etc cases, too, if you're up for it.

**Comment by TheGiddyLimit** [comment]
@symposion In case you weren't aware, my Discord account got suspended yesterday. For the time being, I'm `Giddy##6559`. I'll have missed any messages sent after ~8pm GMT.

**Pull request merged**
