### PR TITLE
More json for LMoP.json

### PR DESCRIPTION
**Pull request by l9f**
Here, spaces converted to tabs.

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
Aha, I was hoping you'd re-appear. Currently working on a Python script to rip the adventures from FantasyGrounds modules - don't worry about providing any JSON for now. The script will take care of the bulk of the text, then we'll need to go through and fix formatting/add links etc. It's happening, though.

**Comment by l9f** [comment]
Got it. Awesome. Will be happy to help link and format when your script is ready.

Do we have some sort of dev doc that shows all the different formatting syntax available? I.e. all the different {@xyz foo} tags?

**Comment by Temp345** [comment]
Hello.
Sorry for hijacking this, but I can't find a way to create a new issue in this new repository
(never used github before).

I wanted to report something: only spells from the PHB are correctly linked from
the spell list of a monster of the bestiary. Example: See bestiary -> Aerisi Kalinoth.
If you click on the spell **Storm Sphere** it opens the spell list but since _phb is
added as suffix in the link the spell is not found (since it's from EEPC and/or XGE). 

There is no more a online version of 5etools, right? You have to download it and use it locally?

Sorry again for derailing this pull request.

**Comment by TheGiddyLimit** [comment]
I wasn't aware there were creatures that used non-PHB spells, interesting. That's not trivially fixable; I'll have to have a think about it.

The online version will return soon(tm) at 5etools.com, but until then you can use: [https://thegiddylimit.github.io/](https://thegiddylimit.github.io/)

**Comment by TheGiddyLimit** [comment]
Pre-alpha footage hot off the presses: [https://gfycat.com/RealisticFocusedJackrabbit](https://gfycat.com/RealisticFocusedJackrabbit)

Site UI is basically done (last thing is to make a "DM read aloud" box style, and use that instead of the green "sidebar" boxes as appropriate). 

Ripper script still needs some work, but it seems to output everything, just not necessarily in the right way (e.g. all the underlined text in the clip is literally just that, it needs to be linked). I think almost all of it can be automated, though, so that's good news - aiming for minimal manual work. I want to be able to add all the other adventures in ~5 mins each. If that's not possible, I'll call in the troops. Sadly, I've got a pretty packed week, so I'm not sure how much I'll be able to get done. But it's _getting close_.

**Comment by l9f** [comment]
That looks nice. Suggestion though: should all the adventures go on one page? Or should there be a list that then pops up a new tab? Wondering if it will get too cluttered with all the adventures on one page, or will the sidebar collapse at the top level?

**Comment by TheGiddyLimit** [comment]
There are two pages - the first is just a list of adventures, which I might remove the chapters from if it gets too cluttered. There's a search on there anyway, so I'm not too worried about it. 

The second is the text/"book" view, which will only load the adventure you want to view. That sidebar will only ever have the contents of one adventure. 

Good enough?

**Comment by l9f** [comment]
That should do it. :)

**Comment by TheGiddyLimit** [comment]
[it's live](https://thegiddylimit.github.io/adventures.html)

**Comment by l9f** [comment]
Looking forward to testing it out.

**Pull request closed without merging**
