### PR TITLE
Cults and Boons, MTF Fluff - Formatting Fixes

### PR DESCRIPTION
**Pull request by badooga**
Fixed line spacing, missing tooltips and headers, and unintentional typos (e.x. extra spaces) with the intention of avoiding any changes to the actual content.

### CODE REVIEW

**Comment by badooga** [comment]
Quotes have been revised according to proper standards.

As for the Cult of Belzenlok, I made edits to its current version (line spacing stuff), which is why it's included in the pull request.

**Comment by TheGiddyLimit** [comment]
There's still the issue of wrapping strings in title-less objects, which, similar to adding empty blocks for spacing, is not desirable. The formatting is (and will be) better fixed through CSS.

Aside from that, it's 1am here. I'll go through that 10k line diff when I'm not about to fall asleep.

**Comment by badooga** [comment]
Somehow the line spacing seems to have been fixed on my end, with the reason probably being that pretty much everything is uniformly nested now (if you scroll through the files really quickly in a code editor, it's actually pretty satisfying)... when I do the other fluff files, I'll probably try to get the same thing. In any case though, better CSS will be a much more powerful tool to use for formatting.

**Comment by TheGiddyLimit** [comment]
I see we've now completely re-formatted the cultsboons file 😅 

Don't think that's going to fly, I'm afraid.

**Comment by badooga** [comment]
Whoops, my bad. I used some Python magic to edit stuff automatically, but then I had to re-beautify the code, and I used a bad extension for that. Luckily, there was another one out there that is identical to the original format.

**Comment by TheGiddyLimit** [comment]
Not quite, it seems. We indent with tabs, rather than spaces. If you wouldn't mind...

**Comment by TheGiddyLimit** [comment]
Strangely, the diff is still the entire file. What encoding are you saving these as? And what line endings? It should be UTF-8 encoding; the line endings are a little less organised--seems the original fluff file is using `LF` and the cultsboons file using `CLRF`.

**Comment by TheGiddyLimit** [comment]
Closing, because it'll be merged with the main repo, and sorting a pointless merge conflict is not something I'm interested in spending time on.

**Pull request closed without merging**
