### PR TITLE
Class list parser for spells in Text Converter

### PR DESCRIPTION
**Pull request by Delta-Duhr**
I think I've fixed the bug I introduced, and it should now work correctly. Hopefully.

### CODE REVIEW

**Comment by Delta-Duhr** [comment]
Another bug: doesn't work for spells without "At Higher Levels" scaling. Sorry for the multiple pull requests.

**Comment by Daniel-Worrall** [comment]
You can just edit the pull request, and not open multiple.

**Comment by Delta-Duhr** [comment]
So sorry about that, I haven't used github in a long time

**Comment by TheGiddyLimit** [comment]
Cheers; merged into main repo for next release.

**Pull request closed without merging**
